---
name: SmartArrow
main: cl4m1n3\smartarrow\SmartArrow
api:
- 5.0.0
version: 1.2.1
php:
- 8.1
author: cl4m1n3

permissions:
  use.smartarrow:
    description: Allows you to use the /smartarrow command
    default: op
...