---
name: SmartArrow
main: smartarrow\Loader
api:
- 3.0.0-ALPHA7
version: 2.1.0
author: cl4m1n3

permissions:
  use.smartarrow:
    description: Allows you to use the /smartarrow command
    default: op
...